### PR TITLE
Update reference documentation to 5.0

### PR DESCRIPTION
**Pull request by fredericDelaporte**
~~I have not kept strange "layout" text previous files were having.~~
I have re-saved all files to utf8 with bom (I should check if there is some option in docbook for that instead) and added back previous meta.
I have added the html5 doctype for having those pages rendered in standard mode instead of quirks mode.
Previous css kept, it has an additional rule at its end.

### CODE REVIEW

**Comment by hazzik** [comment]
I think we want to copy 4.1 into a subfolder (#7). I'll do it later today.

**Comment by fredericDelaporte** [comment]
I have added back includes and layout override in each files. I have also added a proposition for previous version of reference documentation.

I have seen that some direct fixes were made in the documentation, and at least some of them were not done in its DocBook source. So we likely should report those fixes in them and regen again the files.

**Comment by fredericDelaporte** [comment]
Updated with latest changes.

**Comment by fredericDelaporte** [comment]
Re-updated with latest change, squashed a bit, added v3.3 reference taken from SourceForge 3.4.1 zip, v2.1 from SourceForge 2.1.2 zip, and added another proposal: including other formats like pdf and chm.

But chm may cause us undue bug reports due to a mishandled [Windows security feature](https://stackoverflow.com/a/11438732/1178314) causing it to load blank content until unlocking the file.

**Comment by fredericDelaporte** [comment]
Re-updated with latest changes (including "DocGlitches").

**Comment by hazzik** [comment]
Thanks a lot

**Comment by kenny-evitt** [comment]
@fredericDelaporte @hazzik Thanks!

**Pull request merged**
